version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
    default_reviewers:
      - "quanganh206"
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"
    target_branch: "develop"
    default_labels:
      - "submodules"
    allowed_updates:
      - match:
          update_type: "all"
    default_reviewers:
      - "quanganh206"